### ISSUE TITLE
Feature request: Allow grant level for user

### ISSUE THREAD

**Issue by clxnetom** [StefanoMartin/ArangoRB#5]
Would it be possible update the ArangoUser.grant method to allow the setting of a specific level for a grant?

```Ruby
  def grant(database: @@database) # TESTED
    database = database.database if database.is_a?(ArangoDatabase)
    body = { "grant" => "rw" }.to_json
    request = @@request.merge({ :body => body })
    result = self.class.put("/_api/user/#{@user}/database/#{database}", request)
    return_result result: result, caseTrue: true
  end
```

At the moment it is set to "rw", both here and in the ArangoDatabase class. Since I'm new to ArangoDB I'm not sure if access levels are a new feature in version 3.2 or not, but it sure would be nice to have.

**Comment by StefanoMartin** [comment]
I will try to implement it.

Currently I am working to create a new version of ArangoRB. I was planning to do ArangoRB 1.5, but it is resulting in a major release (probably ArangoRB 2.0). 

You can see the evolving in the branch arangorb_1_5 under the folder lib3.

**Comment by StefanoMartin** [comment]
I gave a look on the Documentation. 
Until 3.1 it was possible only to set up "rw" and "none". From 3.2 it is possible to set up "ro" too. 

> 
> A JSON object with these properties is required:
> 
> grant: Use "rw" to set the database access level to Administrate . Use "ro" to set the database access level to Access. Use "none" to set the database access level to No access.


I will implement "ro" in the next release.

**Comment by StefanoMartin** [comment]
I see that the creation for the next release requires quite a lot of time.
For the moment I implement this enhancement in a little patch (arangorb-1.4.1).
You can use it with the following command: myUser.grant_read database: "MyDatabase"
