### ISSUE TITLE
Failed to create a collection of type `Edge`

### ISSUE THREAD

**Issue by dcram** [StefanoMartin/ArangoRB#6]
I tried to create an edge collection as documented with the following piece of code:

```ruby
c = ArangoCollection.new collection: "coll1", database: "db1", type: "Edge"
c.create
```

The collection is created, but its type is `document`. That makes it impossible to create graphs...

**Comment by dcram** [comment]
After having a look at the [examples](https://github.com/StefanoMartin/ArangoRB/blob/master/examples/year.rb), I realized that the right way to do this is the method #create_edge_collection:

```ruby
c = ArangoCollection.new collection: "coll1", database: "db1"
c.create_edge_collection
```

The [Readme](https://github.com/StefanoMartin/ArangoRB#arangocollection) on that point is either out of date either or just misleading.

Thx!

**Comment by StefanoMartin** [comment]
I found the bug. I forgot to check the instance variable when using the method "create" of the class.

However if you write this:

```
c = ArangoCollection.new collection: "coll1", database: "db1"
c.create type: "Edge"
```
the output should be fine.

I will see if to implement a bug correction on this release or implement it directly in ArangoRB 2.0.

**Comment by StefanoMartin** [comment]
I fixed the bug. You can find it correct in the version arangorb-1.4.1.
