### ISSUE TITLE
How to get collection.allDocuments with sorting on an attribute

### ISSUE THREAD

**Issue by vishalsingh123** [StefanoMartin/ArangoRB#8]

**Comment by StefanoMartin** [comment]
The method allDocuments uses `PUT /_api/simple/all` request. 
You can find the documentation of this request on the ArangoDB documentation here: https://docs.arangodb.com/3.3/HTTP/SimpleQuery/
This request does not give possibility to sort.

If you want to have a more sophisticated retrieving, I suggest you use an AQL request.
In your case:
```
aql = ArangoAQL.new query: "FOR doc IN name_collection SORT doc.name_attribute RETURN doc"
aql.execute
```

Let me know if this solve the issue and any suggestion for improvements is welcome.

**Comment by vishalsingh123** [comment]
Thanks StefanoMartin .. 
I can use AQL option but was looking for any option on collection object ..
